---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: maestro-k8s
  namespace: default

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: maestro-k8s
  namespace: default
rules:
- apiGroups:
  - ""
  - "*"
  resources:
  - "*"
  verbs:
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maestro-k8s-global
subjects:
- kind: ServiceAccount
  name: maestro-k8s
  namespace: default
roleRef:
  kind: ClusterRole
  name: maestro-k8s
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-deps
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maestro-k8s
  labels:
    app: maestro-k8s
    release: latest
spec:
  selector:
    matchLabels:
      app: maestro-k8s
  template:
    metadata:
      labels:
        app: maestro-k8s
    spec:
      serviceAccountName: maestro-k8s
      volumes:
      - name: go-deps
        persistentVolumeClaim:
          claimName: go-deps
      containers:
      - name: maestro-k8s
        image: maestro-k8s
        imagePullPolicy: Always
        volumeMounts:
          - name: go-deps
            mountPath: /go
        resources:
          requests:
            memory: 512Mi
            cpu: "1"
          limits:
            memory: 1024Mi
            cpu: "2"
        command:
        - "go"
        - "test"
        - "./..."
